# -*- coding: utf-8 -*-
# """
# Created on Thu Apr  3 08:47:26 2025

# @author: Scotty Lumb
# """




ra_folder_structure:
  client:
    project_folder:
      analysis: {}
      gis:
        plots: {}
        overlays: {}
      git: {}
      src: {}
